module.exports = {
  qualityTitle: '海报清晰度', standardQuality: '标准', ultraQuality: '8K 超清',
  ultraHint: '8K 海报为 4318 × 7680 像素，生成较慢；设备不支持时可切回标准。',
  ultraFailed: '8K 未能生成，请切换标准后重试',
  genericTitle: '测测你的 AITI · AI 使用风格',
  ordinaryTitle: '我是【{typeName}】,测测你是我的搭子还是宿敌?',
  hiddenTitle: '我抽到了 AITI 隐藏款【AI 驯兽师】,你敢测吗?',
  friendTitle: '你的朋友是【{typeName}】',
  friendLoading: '正在读取朋友的类型…',
  friendUnavailable: '暂时无法读取朋友的结果，你可以先测测自己的类型。',
  timelineHint: '点击微信提供的「前往小程序」，查看邀请并开始测试。',
  localNote: '暂时无法附带你的类型，分享将作为测试邀请。',
  saving: '正在生成…', saved: '海报已保存到相册', failed: '保存失败，请稍后重试',
  albumTitle: '允许保存海报', albumText: '请在设置中开启「保存到相册」，返回后重新点击保存海报。',
  settings: '前往设置', close: '暂不保存',
  privacyFailed: '请先同意隐私保护指引，再保存海报。',
  privacyTitle: '保存前请阅读隐私保护指引',
  privacyText: '保存海报需要使用相册写入功能。请阅读并同意隐私保护指引后继续。',
  privacyRead: '阅读隐私保护指引', privacyAgree: '同意并继续',
};
